### PR TITLE
Adds German translations

### PR DESCRIPTION
**Pull request by vjaritz**
I added a German translation. Never worked with git or kotlin before and just tried to make changes analogue to what was already there.
Translations for hours and minutes are very basic, not considering e.g. "Mitternacht" (midnight), as "halb Mitternacht" doesn't sound right and more logic would need to be added for that.
Also, southern German uses "three quarters of hour+1" instead of standard/northern German "one quarter before hour+1". I would like to add this as well, but I guess this would have to be included as its own language(?), and I don't know if you want the project spammed with dialects. ;-)

### CODE REVIEW

**Comment by tuur29** [comment]
Hi!

Your initial commit definitely looks good! Just to be safe, could you confirm this output is correct:

```
00:00 -> gerade zwölf
00:01 -> gerade zwölf
01:03 -> kurz nach eins
02:05 -> kurz nach zwei
03:07 -> kurz nach drei
04:10 -> viertel nach vier
05:14 -> viertel nach fünf
06:15 -> viertel nach sechs
07:16 -> viertel nach sieben
08:20 -> halb neun
09:29 -> halb zehn
09:30 -> halb zehn
09:31 -> halb zehn
09:35 -> halb zehn
09:36 -> halb zehn
10:41 -> viertel vor elf
11:50 -> kurz vor zwölf
12:53 -> kurz vor eins
12:55 -> kurz vor eins
13:57 -> kurz vor zwei
14:59 -> gerade drei
15:00 -> gerade drei
23:50 -> kurz vor zwölf
```

Could you give me a list of edge cases around the problem areas you mentioned (eg. Mitternacht and I'm guessing the same around noon?), something like the output above would be fine. I'll add these more complex cases myself.

About the southern German dialect: This would indeed have to become a custom language. I'm fine adding this, but I suggest we wait until the normal variant of German has been added. It will be easier to copy and change it that to talk about multiple dialects at once.

**Comment by vjaritz** [comment]
The test output is correct.

I would have fun to think about how to do the midnight case myself first, i think - if you don't mind. Shouldn't be too difficult. But I will start creating test cases for them to begin with.

**Comment by vjaritz** [comment]
Okay, I added something for midnight. It is not really common to use "Mittag" for noon, so I left that out.

Here are some tests and expected outcome:

23:28 -> halb zwölf
23:34 -> halb zwölf
23:49 -> viertel vor zwölf
23:51 -> kurz vor Mitternacht 
23:59 -> gerade Mitternacht
00:01 -> gerade Mitternacht
00:08 -> kurz nach Mitternacht
00:11 -> viertel nach zwölf
11:51 -> kurz vor zwölf 
11:59 -> gerade zwölf
12:01 -> gerade zwölf
12:08 -> kurz nach zwölf

I hope I didn't break any logic or the syntax. Haven't found out how to run the code yet, so right now it's all pretty blind. :-D

**Comment by tuur29** [comment]
Thanks for the update. I've created a playground for you to test your code on: [Link](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS4zLjYxIiwiY29kZSI6Ii8qKlxuICogWW91IGNhbiB1c2UgdGhpcyBwbGF5Z3JvdW5kIHRvIHRlc3QgeW91ciBvd24gVHJhbnNsYXRpb24gY2xhc3NcbiAqIGZvciB0aGUgRnV6enljbG9jayBBbmRyb2lkIGFwcDogaHR0cHM6Ly9naXRodWIuY29tL3R1dXIyOS9mdXp6eWNsb2NrL1xuICogSXQgaXMgYmFzZWQgb24gdGhlIFRlc3RHZW5lcmF0b3IgY2xhc3MuXG4gKiBcbiAqIEhvdyB0byB1c2U6XG4gKiAtIEVkaXQgdGhlIHN0cmluZyB2YWx1ZXMgaW5zaWRlIHRoZSBnZW5lcmF0b3IgZnVuY3Rpb24gYmVsb3cuXG4gKiAtIFByZXNzIFwicGxheVwiIGljb24gaW4gdG9wIHJpZ2h0IGNvcm5lci5cbiAqIC0gT25jZSBvdXRwdXQgaXMgY29ycmVjdCwgZm9sbG93IHRoZSByZXN0IG9mIHRoZSBndWlkZTogaHR0cHM6Ly9naXRodWIuY29tL3R1dXIyOS9mdXp6eWNsb2NrL2Jsb2IvbWFzdGVyL3NoYXJlZC9SRUFETUUubWRcbiAqIFxuICogVGhlIFwiZ2VuZXJhdGVcIiBmdW5jdGlvbiB3aWxsIGJlIGFuIGV4YWN0IGNvcHkgb2YgdGhlIG9uZSBidW5kbGVkIHdpdGggdGhlIGFwcC5cbiAqL1xuXG5jbGFzcyBGdXp6eVRleHRDdXN0b20ge1xuXG4gICAgLy8gaG91ciBpcyBhIDI0LWhvdXIgYmFzZWQgaW50ZWdlclxuICAgIGZ1biBnZW5lcmF0ZShob3VyOiBJbnQsIG1pbjogSW50KTogU3RyaW5nIHtcblxuICAgICAgICAvLyBjb252ZXJ0IGZyb20gbWludXRlIGNvdW50IHRvIGZ1enp5IHRleHRcbiAgICAgICAgdmFsIG1pbnRleHQgPSB3aGVuIHtcbiAgICAgICAgICAgIG1pbiA8IDIgLT4gXCJnZXJhZGVcIlxuICAgICAgICAgICAgbWluIDwgMTAgLT4gXCJrdXJ6IG5hY2hcIlxuICAgICAgICAgICAgbWluIDwgMjAgLT4gXCJ2aWVydGVsIG5hY2hcIlxuICAgICAgICAgICAgbWluIDwgNDAgLT4gXCJoYWxiXCIgLy8gaG91ciBzd2l0Y2hlcyBoZXJlXG4gICAgICAgICAgICBtaW4gPCA1MCAtPiBcInZpZXJ0ZWwgdm9yXCJcbiAgICAgICAgICAgIG1pbiA8IDU4IC0+IFwia3VyeiB2b3JcIlxuICAgICAgICAgICAgZWxzZSAtPiBcImdlcmFkZVwiXG4gICAgICAgIH1cblxuICAgICAgICAvLyBnZXJtYW4gdXNlcyBcImhhbGYgPGhvdXIrMT5cIlxuICAgICAgICB2YWwgaG91cnRleHQgPSBpZiAobWluIDwgMjApIHtcbiAgICAgICAgICAgIHdoZW4ge1xuICAgICAgICAgICAgICAgIGhvdXIgJSAxMiA9PSAxIC0+IFwiZWluc1wiXG4gICAgICAgICAgICAgICAgaG91ciAlIDEyID09IDIgLT4gXCJ6d2VpXCJcbiAgICAgICAgICAgICAgICBob3VyICUgMTIgPT0gMyAtPiBcImRyZWlcIlxuICAgICAgICAgICAgICAgIGhvdXIgJSAxMiA9PSA0IC0+IFwidmllclwiXG4gICAgICAgICAgICAgICAgaG91ciAlIDEyID09IDUgLT4gXCJmw7xuZlwiXG4gICAgICAgICAgICAgICAgaG91ciAlIDEyID09IDYgLT4gXCJzZWNoc1wiXG4gICAgICAgICAgICAgICAgaG91ciAlIDEyID09IDcgLT4gXCJzaWViZW5cIlxuICAgICAgICAgICAgICAgIGhvdXIgJSAxMiA9PSA4IC0+IFwiYWNodFwiXG4gICAgICAgICAgICAgICAgaG91ciAlIDEyID09IDkgLT4gXCJuZXVuXCJcbiAgICAgICAgICAgICAgICBob3VyICUgMTIgPT0gMTAgLT4gXCJ6ZWhuXCJcbiAgICAgICAgICAgICAgICBob3VyICUgMTIgPT0gMTEgLT4gXCJlbGZcIlxuICAgICAgICAgICAgICAgIGVsc2UgLT4gd2hlbiAoaG91cikge1xuICAgICAgICAgICAgICAgICAgICAxMiAtPiBcInp3w7ZsZlwiXG4gICAgICAgICAgICAgICAgICAgIGVsc2UgLT4gd2hlbiB7XG5cdFx0XHRcdFx0XHRtaW4gPCAxMCAtPiBcIk1pdHRlcm5hY2h0XCJcblx0XHRcdFx0XHRcdGVsc2UgLT4gXCJ6d8O2bGZcIlxuXHRcdFx0XHRcdH1cdFx0XHRcdFxuICAgICAgICAgICAgICAgIH1cbiAgICAgICAgICAgIH1cbiAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgIHdoZW4ge1xuICAgICAgICAgICAgICAgIGhvdXIgJSAxMiA9PSAwIC0+IFwiZWluc1wiXG5cdFx0XHRcdGhvdXIgJSAxMiA9PSAxIC0+IFwiendlaVwiXG4gICAgICAgICAgICAgICAgaG91ciAlIDEyID09IDIgLT4gXCJkcmVpXCJcbiAgICAgICAgICAgICAgICBob3VyICUgMTIgPT0gMyAtPiBcInZpZXJcIlxuICAgICAgICAgICAgICAgIGhvdXIgJSAxMiA9PSA0IC0+IFwiZsO8bmZcIlxuICAgICAgICAgICAgICAgIGhvdXIgJSAxMiA9PSA1IC0+IFwic2VjaHNcIlxuICAgICAgICAgICAgICAgIGhvdXIgJSAxMiA9PSA2IC0+IFwic2llYmVuXCJcbiAgICAgICAgICAgICAgICBob3VyICUgMTIgPT0gNyAtPiBcImFjaHRcIlxuICAgICAgICAgICAgICAgIGhvdXIgJSAxMiA9PSA4IC0+IFwibmV1blwiXG4gICAgICAgICAgICAgICAgaG91ciAlIDEyID09IDkgLT4gXCJ6ZWhuXCJcbiAgICAgICAgICAgICAgICBob3VyICUgMTIgPT0gMTAgLT4gXCJlbGZcIlxuICAgICAgICAgICAgICAgIGVsc2UgLT4gd2hlbiAoaG91cikge1xuICAgICAgICAgICAgICAgICAgICAxMSAtPiBcInp3w7ZsZlwiXG4gICAgICAgICAgICAgICAgICAgIGVsc2UgLT4gd2hlbiB7XG5cdFx0XHRcdFx0XHRtaW4gPiA1MSAtPiBcIk1pdHRlcm5hY2h0XCJcblx0XHRcdFx0XHRcdGVsc2UgLT4gXCJ6d8O2bGZcIlxuXHRcdFx0XHRcdH1cbiAgICAgICAgICAgICAgICB9XG4gICAgICAgICAgICB9XG4gICAgICAgIH1cblxuICAgICAgICByZXR1cm4gXCIkbWludGV4dFxcbiRob3VydGV4dFwiXG4gICAgfVxufVxuXG4vLyBHZW5lcmF0ZSB0ZXN0IG91dHB1dCAoZG9lc24ndCBuZWVkIGVkaXRpbmcpXG5mdW4gbWFpbigpIHtcbiAgICB2YWwgdGltZXMgPSBhcnJheU9mKCAvLyB0aW1lcyBhcmUgMjQtaG91ciBiYXNlZFxuLy8gICAgICAgICBpbnRBcnJheU9mKDAsMCksXG4vLyAgICAgICAgIGludEFycmF5T2YoMCwxKSxcbi8vICAgICAgICAgaW50QXJyYXlPZigxLDMpLFxuLy8gICAgICAgICBpbnRBcnJheU9mKDIsNSksXG4vLyAgICAgICAgIGludEFycmF5T2YoMyw3KSxcbi8vICAgICAgICAgaW50QXJyYXlPZig0LDEwKSxcbi8vICAgICAgICAgaW50QXJyYXlPZig1LDE0KSxcbi8vICAgICAgICAgaW50QXJyYXlPZig2LDE1KSxcbi8vICAgICAgICAgaW50QXJyYXlPZig3LDE2KSxcbi8vICAgICAgICAgaW50QXJyYXlPZig4LDIwKSxcbi8vICAgICAgICAgaW50QXJyYXlPZig5LDI5KSxcbi8vICAgICAgICAgaW50QXJyYXlPZig5LDMwKSxcbi8vICAgICAgICAgaW50QXJyYXlPZig5LDMxKSxcbi8vICAgICAgICAgaW50QXJyYXlPZig5LDM1KSxcbi8vICAgICAgICAgaW50QXJyYXlPZig5LDM2KSxcbi8vICAgICAgICAgaW50QXJyYXlPZigxMCw0MSksXG4vLyAgICAgICAgIGludEFycmF5T2YoMTEsNTApLFxuLy8gICAgICAgICBpbnRBcnJheU9mKDEyLDUzKSxcbi8vICAgICAgICAgaW50QXJyYXlPZigxMiw1NSksXG4vLyAgICAgICAgIGludEFycmF5T2YoMTMsNTcpLFxuLy8gICAgICAgICBpbnRBcnJheU9mKDE0LDU5KSxcbi8vICAgICAgICAgaW50QXJyYXlPZigxNSwwKSxcbi8vICAgICAgICAgaW50QXJyYXlPZigyMyw1MCksXG4gICAgICAgIGludEFycmF5T2YoMjMsMjgpLCAvLyBoYWxiIHp3w7ZsZlxuICAgICAgICBpbnRBcnJheU9mKDIzLDM0KSwgLy8gaGFsYiB6d8O2bGZcbiAgICAgICAgaW50QXJyYXlPZigyMyw0OSksIC8vIHZpZXJ0ZWwgdm9yIHp3w7ZsZlxuICAgICAgICBpbnRBcnJheU9mKDIzLDUxKSwgLy8ga3VyeiB2b3IgTWl0dGVybmFjaHRcbiAgICAgICAgaW50QXJyYXlPZigyMyw1OSksIC8vIGdlcmFkZSBNaXR0ZXJuYWNodFxuICAgICAgICBpbnRBcnJheU9mKDAsMSksIC8vIGdlcmFkZSBNaXR0ZXJuYWNodFxuICAgICAgICBpbnRBcnJheU9mKDAsOCksIC8vIGt1cnogbmFjaCBNaXR0ZXJuYWNodFxuICAgICAgICBpbnRBcnJheU9mKDAsMTEpLCAvLyB2aWVydGVsIG5hY2ggenfDtmxmXG4gICAgICAgIGludEFycmF5T2YoMTEsNTEpLCAvLyBrdXJ6IHZvciB6d8O2bGZcbiAgICAgICAgaW50QXJyYXlPZigxMSw1OSksIC8vIGdlcmFkZSB6d8O2bGZcbiAgICAgICAgaW50QXJyYXlPZigxMiwxKSwgLy8gZ2VyYWRlIHp3w7ZsZlxuICAgICAgICBpbnRBcnJheU9mKDEyLDgpLCAvLyBrdXJ6IG5hY2ggenfDtmxmXG4gICAgKVxuXG4gICAgdGltZXMuZm9yRWFjaCB7XG4gICAgICAgIHZhbCAoaG91ciwgbWluKSA9IGl0XG4gICAgICAgIHZhbCBnZW5lcmF0b3IgPSBGdXp6eVRleHRDdXN0b20oKVxuICAgICAgICB2YWwgdGV4dCA9IGdlbmVyYXRvci5nZW5lcmF0ZShob3VyLCBtaW4pXG4gICAgICAgICAgICAucmVwbGFjZShcIlxcblwiLCBcIiBcIilcbiAgICAgICAgcHJpbnRsbihcIiR7aG91ci50b1N0cmluZygpLnBhZFN0YXJ0KDIsICcwJyl9OiR7bWluLnRvU3RyaW5nKCkucGFkU3RhcnQoMiwgJzAnKX0gLT4gJHRleHRcXG5cIilcbiAgICB9XG59IiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiJ9).
Code wise everything works okay, but `23:51` doesn't match with your expected outcome. Let me know if you want me to take a look. I was planning on releasing this as an update this weekend.

As for the South German dialect: feel free to create a copy of the `FuzzyTextGerman.kt` file called `FuzzyTextGermanSouth.kt`, I'll link it correctly myself. If you don't know how, you can also just send the contents in a comment.

**Comment by vjaritz** [comment]
Well, < 50 equals > 49, not >51. :-D That should do it.
Thanks for the playground!

**Pull request merged**
